// <auto-generated />
namespace GSA_Management_Information_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class initial29 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial29));
        
        string IMigrationMetadata.Id
        {
            get { return "201912100641348_initial29"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
