// <auto-generated />
namespace GSA_Management_Information_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class initial17 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial17));
        
        string IMigrationMetadata.Id
        {
            get { return "201911290713054_initial17"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
