// <auto-generated />
namespace GSA_Management_Information_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class initial115 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial115));
        
        string IMigrationMetadata.Id
        {
            get { return "202004221759367_initial115"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
