// <auto-generated />
namespace GSA_Management_Information_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class initial48 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial48));
        
        string IMigrationMetadata.Id
        {
            get { return "202001150432080_initial48"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
