// <auto-generated />
namespace GSA_Management_Information_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class initial99 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial99));
        
        string IMigrationMetadata.Id
        {
            get { return "202003300223407_initial99"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
